### ISSUE TITLE
Report an error

### ISSUE THREAD

**Issue by LuMingQ** [RekGRpth/ngx_http_upstream_queue_module#2]
Hi, RekGRpth, thanks for your excellent work, it really helps me a lot. 

I compiled the module with nginx-1.24.0 on windows. It basically works fine, but errors of [crit] level will be logged, if a connection in the queue is closed by client. It seems the socket cannot be terminated as expected in that case.

Here is the steps to reproduce the error:
1. Prepare a toy backend-server, which never respond to requests.
2. Run nginx with the appended config file. This config only allows one connection to the backend.
3. Open two browser tabs to 127.0.0.1, Only the first request will be able to reach backend, and the second one has to wait in the queue.
4. Close the second tab. 

Then the error could be found in log:

> 2024/04/08 19:37:22 [info] 6652#12568: *4 client prematurely closed connection, so upstream connection is closed too while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://backend_server/", host: "127.0.0.1"
> 2024/04/08 19:37:22 [debug] 6652#12568: *4 finalize http upstream request: 499
> 2024/04/08 19:37:22 [debug] 6652#12568: *4 finalize http proxy request
> 2024/04/08 19:37:22 [debug] 6652#12568: *4 close http upstream connection: 0
> 2024/04/08 19:37:22 [debug] 6652#12568: *4 free: 0000022A07576C80, unused: 48
> 2024/04/08 19:37:22 [debug] 6652#12568: *4 event timer del: 0: 1712576295907
> 2024/04/08 19:37:22 [debug] 6652#12568: *4 reusable connection: 0
> 2024/04/08 19:37:22 [crit] 6652#12568: *4 closesocket() 0 failed (10038: An operation was attempted on something that is not a socket) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://backend_server/", host: "127.0.0.1"

nginx.conf:

```
worker_processes 128;
error_log logs/error.log debug;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    access_log off;
    keepalive_timeout 0;

    upstream backend_server {
        server 127.0.0.1:10000 max_conns=1;
        queue 1024 timeout=1m;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
             #root html;
             #index index.html;

            proxy_pass http://backend_server;
            proxy_read_timeout 10d;
        }

    }
}
```

Although nginx will continue working properly, I'm not sure whether further problems will be caused. Could this problem be fixed?

**Comment by RekGRpth** [comment]
It seems the bug was introduced by the last commit. Try without it.

**Comment by RekGRpth** [comment]
fixed by https://github.com/RekGRpth/ngx_http_upstream_queue_module/commit/8ce938eb5bc3e785caf1bed1884a63b42fbc7b4b

**Comment by LuMingQ** [comment]
Thanks for your reply. The error still exists. I noticed the modification is made in  "ngx_http_upstream_queue_peer_free". It seems the error happens before this function is called. Below is the complete error_log by following the steps listed above:

the error could be find at "2024/04/09 13:33:14 [crit] 1880#14996"

> 2024/04/09 13:33:08 [debug] 9004#13496: bind() 0.0.0.0:80 #496 
> 2024/04/09 13:33:08 [notice] 9004#13496: using the "select" event method
> 2024/04/09 13:33:08 [debug] 9004#13496: malloc: 000001B46DF47D70:30
> 2024/04/09 13:33:08 [debug] 9004#13496: counter: 0000047047E00080, 1
> 2024/04/09 13:33:08 [notice] 9004#13496: nginx/1.24.0
> 2024/04/09 13:33:08 [info] 9004#13496: OS: 260200 build:9200, "", suite:100, type:1
> 2024/04/09 13:33:08 [debug] 9004#13496: master started
> 2024/04/09 13:33:08 [debug] 9004#13496: close listening 0.0.0.0:80 #496 
> 2024/04/09 13:33:08 [notice] 9004#13496: start worker processes
> 2024/04/09 13:33:08 [debug] 9004#13496: GetModuleFileName: "C:\nginx\nginx.exe"
> 2024/04/09 13:33:08 [notice] 9004#13496: start worker process 1880
> 2024/04/09 13:33:08 [debug] 1880#11788: bind() 0.0.0.0:80 #496 
> 2024/04/09 13:33:08 [debug] 1880#11788: malloc: 000002385F9D8690:30
> 2024/04/09 13:33:08 [debug] 1880#11788: counter: 0000047047E00080, 1
> 2024/04/09 13:33:08 [notice] 1880#11788: nginx/1.24.0
> 2024/04/09 13:33:08 [info] 1880#11788: OS: 260200 build:9200, "", suite:100, type:1
> 2024/04/09 13:33:08 [debug] 1880#11788: worker started
> 2024/04/09 13:33:08 [debug] 9004#13496: WaitForMultipleObjects: 0
> 2024/04/09 13:33:08 [notice] 1880#11788: create thread 14996
> 2024/04/09 13:33:08 [notice] 1880#11788: create thread 12380
> 2024/04/09 13:33:08 [notice] 1880#11788: create thread 1416
> 2024/04/09 13:33:08 [debug] 1880#14996: malloc: 000002385FA05A10:16384
> 2024/04/09 13:33:08 [debug] 1880#14996: malloc: 000002385FA2BE80:237568
> 2024/04/09 13:33:08 [debug] 1880#14996: malloc: 000002385FA65E90:147456
> 2024/04/09 13:33:08 [debug] 1880#12380: cache manager WaitForMultipleObjects: 1
> 2024/04/09 13:33:08 [debug] 1880#14996: malloc: 00000238614A0080:147456
> 2024/04/09 13:33:08 [debug] 1880#14996: select add event fd:496 ev:768
> 2024/04/09 13:33:08 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:08 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:08 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:08 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:08 [debug] 1880#14996: timer delta: 511
> 2024/04/09 13:33:08 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:08 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:08 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:09 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:09 [debug] 1880#14996: timer delta: 502
> 2024/04/09 13:33:09 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:09 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:09 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:09 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:09 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:09 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:09 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:09 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:10 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:10 [debug] 1880#14996: timer delta: 502
> 2024/04/09 13:33:10 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:10 [debug] 1880#14996: select ready 1
> 2024/04/09 13:33:10 [debug] 1880#14996: select read 496
> 2024/04/09 13:33:10 [debug] 1880#14996: post event 000002385FA65E90
> 2024/04/09 13:33:10 [debug] 1880#14996: timer delta: 201
> 2024/04/09 13:33:10 [debug] 1880#14996: posted event 000002385FA65E90
> 2024/04/09 13:33:10 [debug] 1880#14996: delete posted event 000002385FA65E90
> 2024/04/09 13:33:10 [debug] 1880#14996: accept on 0.0.0.0:80, ready: 0
> 2024/04/09 13:33:10 [debug] 1880#14996: malloc: 000002385FA09B60:512
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 accept: 127.0.0.1:51112 fd:560
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 event timer add: 560: 60000:1712640850557
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 reusable connection: 1
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 select add event fd:560 ev:768
> 2024/04/09 13:33:10 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:10 [debug] 1880#14996: select ready 1
> 2024/04/09 13:33:10 [debug] 1880#14996: select read 560
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 post event 000002385FA65F20
> 2024/04/09 13:33:10 [debug] 1880#14996: timer delta: 0
> 2024/04/09 13:33:10 [debug] 1880#14996: posted event 000002385FA65F20
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 delete posted event 000002385FA65F20
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http wait request handler
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 malloc: 000002385FA09D70:1024
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 WSARecv: fd:560 rc:0 441 of 1024
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 reusable connection: 0
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 malloc: 00000238614C4090:4096
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http process request line
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http request line: "GET / HTTP/1.1"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http uri: "/"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http args: ""
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http exten: ""
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 malloc: 000002385FA0EA40:4096
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http process request header line
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Host: 127.0.0.1"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Accept-Language: en-US,en;q=0.5"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Accept-Encoding: gzip, deflate, br"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Connection: keep-alive"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Upgrade-Insecure-Requests: 1"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Sec-Fetch-Dest: document"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Sec-Fetch-Mode: navigate"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Sec-Fetch-Site: none"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header: "Sec-Fetch-User: ?1"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http header done
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 event timer del: 560: 1712640850557
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 generic phase: 0
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 rewrite phase: 1
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 test location: "/"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 using configuration "/"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http cl:-1 max:1048576
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 rewrite phase: 3
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 post rewrite phase: 4
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 generic phase: 5
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 generic phase: 6
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 generic phase: 7
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 access phase: 8
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 access phase: 9
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 access phase: 10
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 post access phase: 11
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 generic phase: 12
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 generic phase: 13
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http init upstream, client timer: 0
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http script copy: "Host"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http script var: "backend_server"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http script copy: "Connection"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http script copy: "close"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http script copy: ""
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http script copy: ""
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Accept-Language: en-US,en;q=0.5"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Accept-Encoding: gzip, deflate, br"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Upgrade-Insecure-Requests: 1"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Sec-Fetch-Dest: document"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Sec-Fetch-Mode: navigate"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Sec-Fetch-Site: none"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header: "Sec-Fetch-User: ?1"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http proxy header:
> "GET / HTTP/1.0
> Host: backend_server
> Connection: close
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> Upgrade-Insecure-Requests: 1
> Sec-Fetch-Dest: document
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Site: none
> Sec-Fetch-User: ?1
> 
> "
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http cleanup add: 00000238614C5078
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 ngx_http_upstream_queue_peer_init
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 ngx_http_upstream_queue_peer_get
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 get rr peer, try: 1
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 peer.get = 0
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 stream socket 564
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 connect to 127.0.0.1:10000, fd:564 #2
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 select add event fd:564 ev:768
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 select add event fd:564 ev:16
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http upstream connect: -2
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 malloc: 000002385F9BC010:128
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 event timer add: 564: 60000:1712640850557
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http finalize request: -4, "/?" a:1, c:2
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http request count:2 blk:0
> 2024/04/09 13:33:10 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:564 wr:1
> 2024/04/09 13:33:10 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:10 [debug] 1880#14996: select ready 1
> 2024/04/09 13:33:10 [debug] 1880#14996: select write 564
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 post event 00000238614A01A0
> 2024/04/09 13:33:10 [debug] 1880#14996: timer delta: 0
> 2024/04/09 13:33:10 [debug] 1880#14996: posted event 00000238614A01A0
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 delete posted event 00000238614A01A0
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http upstream request: "/?"
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http upstream send request handler
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http upstream send request
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 http upstream send request body
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 chain writer buf fl:1 s:441
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 chain writer in: 000002385FA0F694
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 WSASend: fd:564, s:441
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 chain writer out: 0000000000000000
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 event timer del: 564: 1712640850557
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 select del event fd:564 ev:16
> 2024/04/09 13:33:10 [debug] 1880#14996: *1 event timer add: 564: 864000000:1713504790557
> 2024/04/09 13:33:10 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:10 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:11 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:11 [debug] 1880#14996: timer delta: 502
> 2024/04/09 13:33:11 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:11 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:11 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:11 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:11 [debug] 1880#14996: select ready 1
> 2024/04/09 13:33:11 [debug] 1880#14996: select read 496
> 2024/04/09 13:33:11 [debug] 1880#14996: post event 000002385FA65E90
> 2024/04/09 13:33:11 [debug] 1880#14996: timer delta: 370
> 2024/04/09 13:33:11 [debug] 1880#14996: posted event 000002385FA65E90
> 2024/04/09 13:33:11 [debug] 1880#14996: delete posted event 000002385FA65E90
> 2024/04/09 13:33:11 [debug] 1880#14996: accept on 0.0.0.0:80, ready: 0
> 2024/04/09 13:33:11 [debug] 1880#14996: malloc: 000002385FA0A400:512
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 accept: 127.0.0.1:51114 fd:584
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 event timer add: 584: 60000:1712640851930
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 reusable connection: 1
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 select add event fd:584 ev:768
> 2024/04/09 13:33:11 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:11 [debug] 1880#14996: select ready 1
> 2024/04/09 13:33:11 [debug] 1880#14996: select read 584
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 post event 000002385FA66040
> 2024/04/09 13:33:11 [debug] 1880#14996: timer delta: 54
> 2024/04/09 13:33:11 [debug] 1880#14996: posted event 000002385FA66040
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 delete posted event 000002385FA66040
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http wait request handler
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 malloc: 000002385FA0A610:1024
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 WSARecv: fd:584 rc:0 441 of 1024
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 reusable connection: 0
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 malloc: 000002385FA10A60:4096
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http process request line
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http request line: "GET / HTTP/1.1"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http uri: "/"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http args: ""
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http exten: ""
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 malloc: 000002385FA8DEB0:4096
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http process request header line
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Host: 127.0.0.1"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Accept-Language: en-US,en;q=0.5"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Accept-Encoding: gzip, deflate, br"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Connection: keep-alive"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Upgrade-Insecure-Requests: 1"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Sec-Fetch-Dest: document"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Sec-Fetch-Mode: navigate"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Sec-Fetch-Site: none"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header: "Sec-Fetch-User: ?1"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http header done
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 event timer del: 584: 1712640851930
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 generic phase: 0
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 rewrite phase: 1
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 test location: "/"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 using configuration "/"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http cl:-1 max:1048576
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 rewrite phase: 3
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 post rewrite phase: 4
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 generic phase: 5
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 generic phase: 6
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 generic phase: 7
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 access phase: 8
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 access phase: 9
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 access phase: 10
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 post access phase: 11
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 generic phase: 12
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 generic phase: 13
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http init upstream, client timer: 0
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http script copy: "Host"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http script var: "backend_server"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http script copy: "Connection"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http script copy: "close"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http script copy: ""
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http script copy: ""
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Accept-Language: en-US,en;q=0.5"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Accept-Encoding: gzip, deflate, br"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Upgrade-Insecure-Requests: 1"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Sec-Fetch-Dest: document"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Sec-Fetch-Mode: navigate"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Sec-Fetch-Site: none"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header: "Sec-Fetch-User: ?1"
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http proxy header:
> "GET / HTTP/1.0
> Host: backend_server
> Connection: close
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate, br
> Upgrade-Insecure-Requests: 1
> Sec-Fetch-Dest: document
> Sec-Fetch-Mode: navigate
> Sec-Fetch-Site: none
> Sec-Fetch-User: ?1
> 
> "
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http cleanup add: 000002385FA11A48
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 ngx_http_upstream_queue_peer_init
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 ngx_http_upstream_queue_peer_get
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 get rr peer, try: 1
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 peer.get = -3
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 add cleanup: 000002385FA8EB04
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 event timer add: 1604288524: 60000:1712640851984
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http upstream connect: -2
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 malloc: 000002385F9BBB90:128
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 event timer add: 0: 60000:1712640851984
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http finalize request: -4, "/?" a:1, c:2
> 2024/04/09 13:33:11 [debug] 1880#14996: *3 http request count:2 blk:0
> 2024/04/09 13:33:11 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:11 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:12 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:12 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:12 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:12 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:12 [debug] 1880#14996: timer delta: 503
> 2024/04/09 13:33:12 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:12 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:13 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:13 [debug] 1880#14996: timer delta: 500
> 2024/04/09 13:33:13 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:13 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:13 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:13 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:13 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:14 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:14 [debug] 1880#14996: timer delta: 500
> 2024/04/09 13:33:14 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:584 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:14 [debug] 1880#14996: select ready 1
> 2024/04/09 13:33:14 [debug] 1880#14996: select read 584
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 post event 000002385FA66040
> 2024/04/09 13:33:14 [debug] 1880#14996: timer delta: 216
> 2024/04/09 13:33:14 [debug] 1880#14996: posted event 000002385FA66040
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 delete posted event 000002385FA66040
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http run request: "/?"
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http upstream check client, write event:0, "/"
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http upstream recv(): 0
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 select del event fd:584 ev:768
> 2024/04/09 13:33:14 [info] 1880#14996: *3 client prematurely closed connection, so upstream connection is closed too while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://backend_server/", host: "127.0.0.1"
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 finalize http upstream request: 499
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 finalize http proxy request
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 close http upstream connection: 0
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 free: 000002385F9BBB90, unused: 48
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 event timer del: 0: 1712640851984
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 reusable connection: 0
> 2024/04/09 13:33:14 [crit] 1880#14996: *3 closesocket() 0 failed (10038: An operation was attempted on something that is not a socket) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://backend_server/", host: "127.0.0.1"
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http finalize request: 499, "/?" a:1, c:1
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http terminate request count:1
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http terminate cleanup count:1 blk:0
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http posted request: "/?"
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http terminate handler count:1
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http request count:1 blk:0
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http close request
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 http log handler
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 run cleanup: 000002385FA8EB04
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 ngx_http_upstream_queue_cleanup_handler
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 event timer del: 1604288524: 1712640851984
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 free: 000002385FA10A60, unused: 0
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 free: 000002385FA8DEB0, unused: 396
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 close http connection: 584
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 reusable connection: 0
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 free: 000002385FA0A610
> 2024/04/09 13:33:14 [debug] 1880#14996: *3 free: 000002385FA0A400, unused: 136
> 2024/04/09 13:33:14 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:14 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:15 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:15 [debug] 1880#14996: timer delta: 514
> 2024/04/09 13:33:15 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:15 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:15 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:15 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:15 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:15 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:15 [debug] 1880#14996: timer delta: 503
> 2024/04/09 13:33:15 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:15 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:15 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:15 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:15 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:16 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:16 [debug] 1880#14996: timer delta: 505
> 2024/04/09 13:33:16 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:16 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:16 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:16 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:16 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:16 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:16 [debug] 1880#14996: timer delta: 513
> 2024/04/09 13:33:16 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:16 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:16 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:16 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:16 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:17 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:17 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:17 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:17 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:17 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:17 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:17 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:17 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:17 [debug] 1880#14996: timer delta: 503
> 2024/04/09 13:33:17 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:17 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:17 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:17 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:17 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:18 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:18 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:18 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:18 [debug] 1880#14996: select event: fd:496 wr:0
> 2024/04/09 13:33:18 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:18 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:18 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:18 [notice] 14520#11584: signal process started
> 2024/04/09 13:33:18 [debug] 9004#13496: master WaitForMultipleObjects: 0
> 2024/04/09 13:33:18 [notice] 9004#13496: exiting
> 2024/04/09 13:33:18 [debug] 9004#13496: process: 0 1880 0000000000000200 e:0 j:0
> 2024/04/09 13:33:18 [debug] 1880#11788: worker WaitForMultipleObjects: 1
> 2024/04/09 13:33:18 [notice] 1880#11788: gracefully shutting down
> 2024/04/09 13:33:18 [debug] 1880#12380: cache manager WaitForSingleObject: 0
> 2024/04/09 13:33:18 [notice] 1880#12380: exiting
> 2024/04/09 13:33:18 [debug] 1880#11788: worker exit WaitForMultipleObjects: 2
> 2024/04/09 13:33:18 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:18 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:18 [debug] 1880#14996: select del event fd:496 ev:768
> 2024/04/09 13:33:18 [debug] 1880#14996: close listening 0.0.0.0:80 #496 
> 2024/04/09 13:33:18 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:18 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:18 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:18 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:19 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:19 [debug] 1880#14996: timer delta: 502
> 2024/04/09 13:33:19 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:19 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:19 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:19 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:19 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:19 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:19 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:19 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:19 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:19 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:20 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:20 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:20 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:20 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:20 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:20 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:20 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:20 [debug] 1880#14996: timer delta: 502
> 2024/04/09 13:33:20 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:20 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:20 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:20 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:21 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:21 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:21 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:21 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:21 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:21 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:21 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:21 [debug] 1880#14996: timer delta: 501
> 2024/04/09 13:33:21 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:21 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:21 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:21 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:22 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:22 [debug] 1880#14996: timer delta: 500
> 2024/04/09 13:33:22 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:22 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:22 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:22 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:22 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:22 [debug] 1880#14996: timer delta: 500
> 2024/04/09 13:33:22 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:22 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:22 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:22 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:23 [debug] 1880#14996: select ready 0
> 2024/04/09 13:33:23 [debug] 1880#14996: timer delta: 502
> 2024/04/09 13:33:23 [debug] 1880#14996: worker cycle
> 2024/04/09 13:33:23 [debug] 1880#14996: select event: fd:564 wr:0
> 2024/04/09 13:33:23 [debug] 1880#14996: select event: fd:560 wr:0
> 2024/04/09 13:33:23 [debug] 1880#14996: select timer: 500
> 2024/04/09 13:33:23 [debug] 9004#13496: master WaitForMultipleObjects: 258
> 2024/04/09 13:33:23 [notice] 9004#13496: exit
> 2024/04/09 13:33:23 [debug] 9004#13496: run cleanup: 000001B46DF8CFE4
> 2024/04/09 13:33:23 [debug] 9004#13496: cleanup resolver
> 2024/04/09 13:33:23 [debug] 9004#13496: run cleanup: 000001B46DF6530C
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF946F0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF8F510
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF864E0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF85030
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF83010
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF7DF40
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF7CE80
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF7BDC0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF631E0, unused: 0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF74B70, unused: 0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF7F000, unused: 0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF874F0, unused: 0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF8B500, unused: 0
> 2024/04/09 13:33:23 [debug] 9004#13496: free: 000001B46DF906E0, unused: 9973

**Comment by RekGRpth** [comment]
> Prepare a toy backend-server, which never respond to requests.

any bash example?

**Comment by LuMingQ** [comment]
> any bash example?

I opened a tcp server with matlab "Backend=tcpserver(10000)" as backend, whose port is 10000. It can accept tcp connection and receive http requests. This Backend allows a connection keeping alive forever, and no response will be automatically sent back.

By doing this, the first client can build a connection and sent its request to the toy Backend, but it will wait for response forever (if no timeout is set). Then latter connections from other clients are put in the queue. Error happens when we close a waiting client in the queue.

No further problem is observed. After the error, If I let the Backend start to send responses, the queue will start running as expected: the closed client will be skipped.

**Comment by RekGRpth** [comment]
I have already found the reason for the problem and work on its elimination ...

**Comment by RekGRpth** [comment]
fixed by https://github.com/RekGRpth/ngx_http_upstream_queue_module/commit/0d83416edb780ced4d226c404f313132c4c56b14

**Comment by dpy1123** [comment]
hi @RekGRpth, can you explain more about the modifaction?
I can see the goal is to set shared = 1 to avoid connection removal. But in my opinion, when calling `ngx_event_connect_peer` internally will call `ngx_get_connection` anyway, this function will give u->peer->connection a new avaliable freeconnection.
how to keep that shared = 1 setting still avalibale?

**Comment by RekGRpth** [comment]
> can you explain more about the modifaction?

Does the last solution work for you?

**Comment by RekGRpth** [comment]
> I can see the goal is to set shared = 1 to avoid connection removal

No, I set this so that the ngx_close_connection function does not try to close socket 0 of the dummy connection.

**Comment by dpy1123** [comment]
> > can you explain more about the modifaction?
> 
> Does the last solution work for you?

<img width="985" alt="image" src="https://github.com/RekGRpth/ngx_http_upstream_queue_module/assets/3691507/4e28558c-5ec0-4392-9d86-341f32570145">
seems all the requests will return 502.  queue size is set to 10.

**Comment by RekGRpth** [comment]
> when calling `ngx_event_connect_peer` internally will call `ngx_get_connection` anyway

Yes, the dummy connection is overwritten by the real one.

**Comment by dpy1123** [comment]
> > I can see the goal is to set shared = 1 to avoid connection removal
> 
> No, I set this so that the ngx_close_connection function does not try to close socket 0 of the dummy connection.

socket 0 or fd = 0 is the stdin, right? so the root case for the original error is that stdin is closed?

**Comment by RekGRpth** [comment]
> socket 0 or fd = 0 is the stdin, right?

yes

**Comment by RekGRpth** [comment]
> so the root case for the original error is that stdin is closed?

No, initially the error was that I was manually creating a dummy connection rather than taking it from the pool, and then this dummy connection ended up in the pool and an error occurred when using it.

**Comment by RekGRpth** [comment]
> Maybe I should close this dummy connection first?

did

**Comment by RekGRpth** [comment]
> I do a request and then it quickly fullup the queue size ,and cause all the request after that return 502. queue size is set to 10.

Isn't that exactly how it should work?

**Comment by dpy1123** [comment]
I only triggered 1 http call , and then queue filled up. and the 2nd http call will return 502, since queue is full.

<img width="1232" alt="image" src="https://github.com/RekGRpth/ngx_http_upstream_queue_module/assets/3691507/f996db1d-ac3d-4cf3-b783-2608c6ae2314">
above is the calltrace for the very begining, since we return NGX_AGAIN in peer_get, we runs into:
<img width="657" alt="image" src="https://github.com/RekGRpth/ngx_http_upstream_queue_module/assets/3691507/26b6a34d-b9f2-4df0-b8df-85d330688dbb">

and then it comes over and over again, till queue is fulled up:
<img width="1214" alt="image" src="https://github.com/RekGRpth/ngx_http_upstream_queue_module/assets/3691507/5a5fe042-d3dd-4898-b8cd-2f75780da9b1">

**Comment by RekGRpth** [comment]
> I only triggered 1 http call , and then queue filled up. and the 2nd http call will return 502, since queue is full.

I run in one window
```bash
while true; do nc -lp 10000; done
```
then in second window
```sh
curl 127.0.0.1
```
then in third window
```sh
curl 127.0.0.1
```
then in fourth window
```sh
curl 127.0.0.1
```
and no errors
also in fourth window I press Ctrl+C to interrupt and again run, and no errors
my config
```nginx
upstream backend_server {
    server 127.0.0.1:10000 max_conns=1;
    queue 10;
}
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    error_log stderr error;
    access_log off;
    location / {
        keepalive_timeout 0;
        access_log /var/log/nginx/nginx/backend_server.log main;
        error_log /var/log/nginx/nginx/backend_server.err debug;
        proxy_pass http://backend_server;
        proxy_read_timeout 10d;
    }
}
```

**Comment by dpy1123** [comment]
I think its duel to the proxy_connect_timeout config . if u set to 1s, it will run up the queue size.
<img width="823" alt="image" src="https://github.com/RekGRpth/ngx_http_upstream_queue_module/assets/3691507/2e4ebc3a-038f-4cdf-82ed-d644e0333ea0">

**Comment by RekGRpth** [comment]
> I think its duel to the proxy_connect_timeout config . if u set to 1s, it will run up the queue size.

fixed by https://github.com/RekGRpth/ngx_http_upstream_queue_module/commit/524b621f5ebc4ccaa0604aa5e2fed0f407a04c5a

**Comment by dpy1123** [comment]
hi @RekGRpth , although we can avoid queue fillup by if we use `ngx_min(u->conf->connect_timeout, qscf->timeout)`, but we are losing the ability of queue the request with the timeout set by `queue` directive.
Maybe we should test the connection in peer_get phase?

**Comment by RekGRpth** [comment]
> but we are losing the ability of queueing requests with the timeout set by `queue` directive.

Why? It is only when u->conf->connect_timeout < qscf->timeout

**Comment by RekGRpth** [comment]
> Maybe we should test the connection in peer_get phase?

What do you mean?

**Comment by dpy1123** [comment]
> > but we are losing the ability of queueing requests with the timeout set by `queue` directive.
> 
> Why? It is only when u->conf->connect_timeout < qscf->timeout

yes, as we always will config proxy_connect_timeout to a small value like 1s or 3s.  but in queue directive, we will config size like 1k, and timeout like 10-30s. which means queue's timeout will be overwrite by connection timeout in most of cases.

**Comment by RekGRpth** [comment]
> we always will config proxy_connect_timeout to a small value like 1s or 3s.

Why?

**Comment by RekGRpth** [comment]
function ngx_http_upstream_connect ngx_add_timer(c->write, u->conf->connect_timeout) after my function ngx_http_upstream_queue_peer_get return NGX_AGAIN, so single solution is use queue's timeout < connection timeout

**Comment by dpy1123** [comment]
yes, thats the hard part. 
since peer.get happens before ngx_get_connection, we have no idead wether this connection can be established or not.
so is it possible if we test connection first and if connection can't be established we don't add this request in queue?

**Comment by RekGRpth** [comment]
> we test connection first and if connection can't be established

then we add this request to queue

**Comment by dpy1123** [comment]
> are you using [keepalive](https://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) option?

no

**Comment by dpy1123** [comment]
can we change the queue to a hashset liked queue, when the same request comes again, just ignore it.

**Comment by RekGRpth** [comment]
By the way, I have an idea how to remove the connection timeout timer after being queued...

**Comment by RekGRpth** [comment]
> By the way, I have an idea how to remove the connection timeout timer after being queued...

done via https://github.com/RekGRpth/ngx_http_upstream_queue_module/commit/d98f43f96f0b399185298e26b2c4de2ecf5da990

**Comment by dpy1123** [comment]
It works!
btw I'm changing to `ngx_add_timer(&d->connect_timeout, u->conf->connect_timeout / 2);`, make sure clean handler happens before 'retry'.

**Comment by RekGRpth** [comment]
> `ngx_add_timer(&d->connect_timeout, u->conf->connect_timeout / 2);`

applied
